README.md
lib/event_bus/models/event.ex
test/event_bus/event_manager_test.exs
test/event_bus_test.exs

Add optional `occurred_at` and `ttl` fields to `Event` model to track and invalidate events when necessary.

Add optional occurred_at and ttl fields to Event model

---

README.md

This adds notes in the README around configuring `:event_bus` as part of the application supervision tree.
- Issue #15

Add notes around mix.exs config in README

---

CHANGELOG.md
README.md
lib/event_bus.ex
lib/event_bus/application.ex
lib/event_bus/managers/notification.ex
lib/event_bus/managers/observation.ex
lib/event_bus/managers/store.ex
lib/event_bus/managers/subscription.ex
lib/event_bus/managers/topic.ex
lib/event_bus/services/notification.ex
lib/event_bus/services/observation.ex
lib/event_bus/services/subscription.ex
lib/event_bus/services/topic.ex
test/event_bus/managers/notification_test.exs
test/event_bus/managers/observation_test.exs
test/event_bus/managers/store_test.exs
test/event_bus/managers/subscription_test.exs
test/event_bus/managers/topic_test.exs
test/event_bus/services/notification_test.exs
test/event_bus/services/observation_test.exs
test/event_bus/services/subscription_test.exs
test/event_bus_test.exs

//cc @otobus 
Removed support for system event tracing for `notify` action (unnecessary)
Moved internal modules under managers namespace for better documentation
Add subscribed? function to check subscriptions
- Issue NA

Enhancements

---

CHANGELOG.md
lib/event_bus/services/notification.ex
test/event_bus/managers/observation_test.exs
test/event_bus/managers/store_test.exs
test/event_bus/managers/topic_test.exs

//cc @otobus
The current implementation allows all events to create insertion to Store and Observation ETS tables even if there is no subscriber for the topic. This may cause unnecessary operations. 
Fixes https://github.com/otobus/event_bus/issues/27
- Issue: https://github.com/otobus/event_bus/issues/27

Log empty topic listeners to prevent unnecessary ETS inserts

---

lib/event_bus/services/notification.ex

//cc @otobus 
Update log message for empty subscribers to give a clear state of topic registration
- Issue #29

Update log message for empty subscribers

---

CHANGELOG.md
README.md
lib/event_bus.ex
lib/event_bus/managers/store.ex
lib/event_bus/services/store.ex
test/event_bus/services/store_test.exs

//cc @otobus 
Introduce `fetch_event_data` function to fetch only event data
- [NA] Created an issue and defined what the problem is

Introduce fetch_event_data function to fetch only event data

---

CHANGELOG.md
README.md
config/test.exs
lib/event_bus/event_source.ex
lib/event_bus/utils/regex.ex
lib/event_bus/utils/string.ex
test/event_bus/event_source_test.exs
test/event_bus/utils/regex_test.exs
test/event_bus/utils/string_test.exs

//cc @otobus 
Allow optional vars from the configuration for event builder

Allow optional vars from the configuration for event builder

---

README.md
lib/event_bus/utils/base62.ex
lib/event_bus/utils/string.ex
test/event_bus/utils/base62_test.exs
test/event_bus/utils/string_test.exs

//cc @otobus
This enhancement makes unique_id generation distributable across multiple nodes.

Move unique_id functionality to base62 module

---

lib/event_bus/event_source.ex
lib/event_bus/managers/notification.ex
lib/event_bus/managers/observation.ex
lib/event_bus/managers/store.ex
lib/event_bus/managers/subscription.ex
lib/event_bus/managers/topic.ex
lib/event_bus/services/notification.ex
lib/event_bus/services/observation.ex
lib/event_bus/services/subscription.ex
lib/event_bus/services/topic.ex
lib/event_bus/utils/string.ex

Make module alias consistent with service module naming
- Issue: NA

Make module alias consistent with service module naming

---

.travis.yml

//cc @otobus
Add Elixir 1.7 and OTP 21.0 to Travis config
- Issue: https://github.com/otobus/event_bus/issues/38

Add Elixir 1.7 and OTP 21.0 to Travis config

---

CHANGELOG.md
lib/event_bus.ex
lib/event_bus/managers/subscription.ex
test/event_bus/managers/subscription_test.exs

//cc @otobus 
Fix spec for `EventBus.unsubscribe/1`. 
- Issue https://github.com/otobus/event_bus/issues/48

Fix spec for unsubscribe/1. 

---

CHANGELOG.md
lib/event_bus/event_source.ex

The typespec for `time_unit()` actually defines the atom as `:microseconds`, which causes the code as-is to raise Dialyzer errors: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/system.ex#L65
- Issue #52

Fix default @eb_time_unit

---

CHANGELOG.md
README.md
config/test.exs
lib/event_bus/utils/base62.ex
test/event_bus/models/event_test.exs

Normalize time units as their singular, non-underscored versions.
This is in line with the new standards in Erlang 19+
- Issue #54

Normalize time units as their singular, non-underscored versions

---

CHANGELOG.md
lib/event_bus/services/observation.ex
lib/event_bus/services/store.ex
test/event_bus/services/observation_test.exs
test/event_bus/services/store_test.exs
test/event_bus/services/topic_test.exs

//cc @otobus 
Fix Elixir 1.7 warnings for String to Atom conversions

Fix Elixir 1.7 warnings for string to atom conversions

---

.travis.yml
CHANGELOG.md
lib/event_bus/models/event.ex
mix.exs

//cc @otobus 
Update the Travis script to prevent breaks on merges
- Issue #

Update travis script

---

.travis.yml

//cc @otobus
Add Elixir 1.8 and OTP 21.0 to Travis config
- Issue: https://github.com/otobus/event_bus/issues/89

Add Elixir 1.8 and OTP 21.0 to Travis config

---

.travis.yml

//cc @otobus 
Update travis to include elixir `1.9` and otp `22` versions

Update travis to include elixir 1.9 and otp 22 versions

---

CHANGELOG.md
lib/event_bus/services/observation.ex
lib/event_bus/services/store.ex
mix.lock

This safely handles `Store.fetch` when ETS data is missing for some reason in production that avoids  crashing the application.
This safely handles `Store.fetch` when ETS data is missing for some reason in production that avoids  crashing the application.
Also made the helper subscribers be `GenServer` to notify the test process that the event was processed. It also helps `event_bus_test.exs` to correctly capture the log for the test to pass.
- Issue #113

[fix] `Store.fetch` should safely handle missing ETS data and improve test stability

---

README.md

I am using this library for a personal project, and noticed some typos on the Readme file. Described in issue #123

Fixing typos on README file

---

mix.exs

**Describe the bug**
Compiler warnings about :crypto when running `mix deps.compile` in an app that uses `event_bus`.
- Issue #157

Add :crypto to extra_applications to fix warnings when `mix deps.compile`

---

.formatter.exs
.gitignore
CHANGELOG.md
LICENSE.md
README.md
lib/event_bus.ex
lib/event_bus/event_source.ex
lib/event_bus/models/event.ex
lib/event_bus/utils/base62.ex
lib/event_bus/utils/monotonic_time.ex
lib/event_bus/utils/regex.ex
mix.exs

Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the main reference doc for this
Elixir library which leverage on latest features of ExDoc.
- Issue #

Misc doc changes
